#!/usr/bin/env node
/**
 * Render docs/assets/banner-github.html -> banner-github.png.
 *
 * The banner quotes live numbers (version, test count), and before this script
 * existed it was regenerated by hand — so it drifted, and for several releases
 * advertised a stale version and test count. Run this whenever those change:
 *
 *   node scripts/render-banner.mjs            # render
 *   node scripts/render-banner.mjs --check    # fail if the numbers are stale
 *
 * Uses headless Chrome, which is already required for nothing else in this
 * repo — hence the explicit, friendly failure when it is absent rather than a
 * spawn error.
 */

import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, mkdtempSync, copyFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const html = path.join(root, 'docs/assets/banner-github.html')
const png = path.join(root, 'docs/assets/banner-github.png')

const WIDTH = 1280
const HEIGHT = 400
const SCALE = 1.5 // 1920x600 — sharp on HiDPI without bloating the repo

/** The facts the banner asserts, and how to derive each one. */
function currentFacts() {
  const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'))
  return {
    version: `v${pkg.version} stable`,
    runtimeDeps: String(Object.keys(pkg.dependencies ?? {}).length),
  }
}

function checkFacts() {
  const source = readFileSync(html, 'utf8')
  const facts = currentFacts()
  const stale = []

  if (!source.toLowerCase().includes(facts.version.toLowerCase())) {
    stale.push(`version badge does not say "${facts.version}"`)
  }
  const deps = source.match(/<div class="stat-n">(\d+)<\/div>\s*<div class="stat-l">Runtime/)
  if (deps && deps[1] !== facts.runtimeDeps) {
    stale.push(`runtime-dependency count says ${deps[1]}, package.json has ${facts.runtimeDeps}`)
  }

  if (stale.length > 0) {
    console.error('banner is stale:')
    for (const s of stale) console.error(`  - ${s}`)
    console.error('\nEdit docs/assets/banner-github.html, then: node scripts/render-banner.mjs')
    process.exit(1)
  }
  console.log('banner facts are current')
}

function findChrome() {
  const candidates = [
    process.env.CHROME_PATH,
    'google-chrome',
    'google-chrome-stable',
    'chromium',
    'chromium-browser',
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  ].filter(Boolean)

  for (const c of candidates) {
    try {
      execFileSync(c, ['--version'], { stdio: 'ignore' })
      return c
    } catch {
      // Not this one; keep looking.
    }
  }
  return null
}

function render() {
  const chrome = findChrome()
  if (!chrome) {
    console.error('No Chrome or Chromium found. Install one, or set CHROME_PATH.')
    process.exit(1)
  }

  // Chrome writes the screenshot at the scaled size; it cannot also quantise,
  // so the raw render goes to a temp file first.
  const tmp = path.join(mkdtempSync(path.join(tmpdir(), 'banner-')), 'raw.png')
  execFileSync(chrome, [
    '--headless',
    '--disable-gpu',
    '--hide-scrollbars',
    `--force-device-scale-factor=${SCALE}`,
    `--window-size=${WIDTH},${HEIGHT}`,
    `--screenshot=${tmp}`,
    '--virtual-time-budget=4000', // let the webfonts land before capture
    html,
  ], { stdio: 'ignore' })

  if (!existsSync(tmp)) {
    console.error('Chrome produced no screenshot.')
    process.exit(1)
  }

  // Quantising a gradient this dark is safe at 256 colours with dithering, and
  // roughly halves the file. Without ImageMagick, ship the raw render.
  try {
    execFileSync('convert', [tmp, '-strip', '-dither', 'FloydSteinberg', '-colors', '256', png], {
      stdio: 'ignore',
    })
  } catch {
    copyFileSync(tmp, png)
    console.log('(ImageMagick not found — wrote the unquantised render)')
  }

  const bytes = readFileSync(png).length
  console.log(`wrote ${path.relative(root, png)} — ${Math.round(WIDTH * SCALE)}x${Math.round(HEIGHT * SCALE)}, ${(bytes / 1024).toFixed(0)} KB`)
}

if (process.argv.includes('--check')) checkFacts()
else render()
